library(PRROC)
library(AUC)

load("Data/TS1_EVE_CPT1.RData")
load("Data/TS2_EVE_CPT1.RData")
load("Data/TS3_EVE_CPT1.RData")
load("Data/TS4_EVE_CPT1.RData")
load("Data/TS5_EVE_CPT1.RData")

y1 <- as.numeric(ts1$variant_info)
y2 <- as.numeric(ts2$variant_info)
y3 <- as.numeric(ts3$variant_info)
y4 <- as.numeric(ts4$variant_info)
y5 <- as.numeric(ts5$variant_info)

pb1 <- as.numeric(ts1$PHACTboost)
pb2 <- as.numeric(ts2$PHACTboost)
pb3 <- as.numeric(ts3$PHACTboost)
pb4 <- as.numeric(ts4$PHACTboost)
pb5 <- as.numeric(ts5$PHACTboost)

# EVE

eve1 <- as.numeric(ts1$EVE)
eve2 <- as.numeric(ts2$EVE)
eve3 <- as.numeric(ts3$EVE)
eve4 <- as.numeric(ts4$EVE)
eve5 <- as.numeric(ts5$EVE)

chs1 <- which(is.na(eve1)!=1)
chs2 <- which(is.na(eve2)!=1)
chs3 <- which(is.na(eve3)!=1)
chs4 <- which(is.na(eve4)!=1)
chs5 <- which(is.na(eve5)!=1)

values <- c()
eve_table <- c()
pb1_roc <- auc(roc(pb1[chs1], as.factor(1 * (y1[chs1] == 1))))
eve1_roc <- auc(roc(eve1[chs1], as.factor(1 * (y1[chs1] == 1))))
values <- rbind(values, c(pb1_roc, eve1_roc))
l1 <- length(which(y1[chs1]==1))
l2 <- length(which(y1[chs1]==-1))
eve_table <- rbind(eve_table, c(l1,l2))
pb2_roc <- auc(roc(pb2[chs2], as.factor(1 * (y2[chs2] == 1))))
eve2_roc <- auc(roc(eve2[chs2], as.factor(1 * (y2[chs2] == 1))))
values <- rbind(values, c(pb2_roc, eve2_roc))
l1 <- length(which(y2[chs2]==1))
l2 <- length(which(y2[chs2]==-1))
eve_table <- rbind(eve_table, c(l1,l2))
pb3_roc <- auc(roc(pb3[chs3], as.factor(1 * (y3[chs3] == 1))))
eve3_roc <- auc(roc(eve3[chs3], as.factor(1 * (y3[chs3] == 1))))
values <- rbind(values, c(pb3_roc, eve3_roc))
l1 <- length(which(y3[chs3]==1))
l2 <- length(which(y3[chs3]==-1))
eve_table <- rbind(eve_table, c(l1,l2))
pb4_roc <- auc(roc(pb4[chs4], as.factor(1 * (y4[chs4] == 1))))
eve4_roc <- auc(roc(eve4[chs4], as.factor(1 * (y4[chs4] == 1))))
values <- rbind(values, c(pb4_roc, eve4_roc))
l1 <- length(which(y4[chs4]==1))
l2 <- length(which(y4[chs4]==-1))
eve_table <- rbind(eve_table, c(l1,l2))
pb5_roc <- auc(roc(pb5[chs5], as.factor(1 * (y5[chs5] == 1))))
eve5_roc <- auc(roc(eve5[chs5], as.factor(1 * (y5[chs5] == 1))))
values <- rbind(values, c(pb5_roc, eve5_roc))
l1 <- length(which(y5[chs5]==1))
l2 <- length(which(y5[chs5]==-1))
eve_table <- rbind(eve_table, c(l1,l2))

values <- t(values)
values <- as.data.frame(values)
colnames(values) <- c("TS1", "TS2", "TS3", "TS4", "TS5")
rownames(values) <- c("PHACTboost", "EVE")


values_pr <- c()
pp1 <- pr.curve(scores.class0 = pb1[chs1], weights.class0 = (1 * (y1[chs1] == 1)), curve = TRUE)
pp2 <- pr.curve(scores.class0 = eve1[chs1], weights.class0 = (1 * (y1[chs1] == 1)), curve = TRUE)
values_pr <- rbind(values_pr, c(pp1$auc.integral, pp2$auc.integral))
pp3 <- pr.curve(scores.class0 = pb2[chs2], weights.class0 = (1 * (y2[chs2] == 1)), curve = TRUE)
pp4 <- pr.curve(scores.class0 = eve2[chs2], weights.class0 = (1 * (y2[chs2] == 1)), curve = TRUE)
values_pr <- rbind(values_pr, c(pp3$auc.integral, pp4$auc.integral))
pp5 <- pr.curve(scores.class0 = pb3[chs3], weights.class0 = (1 * (y3[chs3] == 1)), curve = TRUE)
pp6 <- pr.curve(scores.class0 = eve3[chs3], weights.class0 = (1 * (y3[chs3] == 1)), curve = TRUE)
values_pr <- rbind(values_pr, c(pp5$auc.integral, pp6$auc.integral))
pp7 <- pr.curve(scores.class0 = pb4[chs4], weights.class0 = (1 * (y4[chs4] == 1)), curve = TRUE)
pp8 <- pr.curve(scores.class0 = eve4[chs4], weights.class0 = (1 * (y4[chs4] == 1)), curve = TRUE)
values_pr <- rbind(values_pr, c(pp7$auc.integral, pp8$auc.integral))
pp9 <- pr.curve(scores.class0 = pb5[chs5], weights.class0 = (1 * (y5[chs5] == 1)), curve = TRUE)
pp10 <- pr.curve(scores.class0 = eve5[chs5], weights.class0 = (1 * (y5[chs5] == 1)), curve = TRUE)
values_pr <- rbind(values_pr, c(pp9$auc.integral, pp10$auc.integral))

values_pr <- t(values_pr)
values_pr <- as.data.frame(values_pr)
colnames(values_pr) <- c("TS1", "TS2", "TS3", "TS4", "TS5")
rownames(values_pr) <- c("PHACTboost", "EVE")

values_eve_roc <- values
values_eve_pr <- values_pr


# CPT-1

cpt1 <- as.numeric(ts1$`CPT-1`)
cpt2 <- as.numeric(ts2$`CPT-1`)
cpt3 <- as.numeric(ts3$`CPT-1`)
cpt4 <- as.numeric(ts4$`CPT-1`)
cpt5 <- as.numeric(ts5$`CPT-1`)

chs1 <- which(is.na(cpt1)!=1)
chs2 <- which(is.na(cpt2)!=1)
chs3 <- which(is.na(cpt3)!=1)
chs4 <- which(is.na(cpt4)!=1)
chs5 <- which(is.na(cpt5)!=1)

values <- c()
cpt_table <- c()
pb1_roc <- auc(roc(pb1[chs1], as.factor(1 * (y1[chs1] == 1))))
p1_roc <- auc(roc(cpt1[chs1], as.factor(1 * (y1[chs1] == 1))))
values <- rbind(values, c(pb1_roc, p1_roc))
l1 <- length(which(y1[chs1]==1))
l2 <- length(which(y1[chs1]==-1))
cpt_table <- rbind(cpt_table, c(l1,l2))
pb2_roc <- auc(roc(pb2[chs2], as.factor(1 * (y2[chs2] == 1))))
p2_roc <- auc(roc(cpt2[chs2], as.factor(1 * (y2[chs2] == 1))))
values <- rbind(values, c(pb2_roc, p2_roc))
l1 <- length(which(y2[chs2]==1))
l2 <- length(which(y2[chs2]==-1))
cpt_table <- rbind(cpt_table, c(l1,l2))
pb3_roc <- auc(roc(pb3[chs3], as.factor(1 * (y3[chs3] == 1))))
p3_roc <- auc(roc(cpt3[chs3], as.factor(1 * (y3[chs3] == 1))))
values <- rbind(values, c(pb3_roc, p3_roc))
l1 <- length(which(y3[chs3]==1))
l2 <- length(which(y3[chs3]==-1))
cpt_table <- rbind(cpt_table, c(l1,l2))
pb4_roc <- auc(roc(pb4[chs4], as.factor(1 * (y4[chs4] == 1))))
p4_roc <- auc(roc(cpt4[chs4], as.factor(1 * (y4[chs4] == 1))))
values <- rbind(values, c(pb4_roc, p4_roc))
l1 <- length(which(y4[chs4]==1))
l2 <- length(which(y4[chs4]==-1))
cpt_table <- rbind(cpt_table, c(l1,l2))
pb5_roc <- auc(roc(pb5[chs5], as.factor(1 * (y5[chs5] == 1))))
p5_roc <- auc(roc(cpt5[chs5], as.factor(1 * (y5[chs5] == 1))))
values <- rbind(values, c(pb5_roc, p5_roc))
l1 <- length(which(y5[chs5]==1))
l2 <- length(which(y5[chs5]==-1))
cpt_table <- rbind(cpt_table, c(l1,l2))

values <- t(values)
values <- as.data.frame(values)
colnames(values) <- c("TS1", "TS2", "TS3", "TS4", "TS5")
rownames(values) <- c("PHACTboost", "CPT-1")


values_pr <- c()
pp1 <- pr.curve(scores.class0 = pb1[chs1], weights.class0 = (1 * (y1[chs1] == 1)), curve = TRUE)
pp2 <- pr.curve(scores.class0 = cpt1[chs1], weights.class0 = (1 * (y1[chs1] == 1)), curve = TRUE)
values_pr <- rbind(values_pr, c(pp1$auc.integral, pp2$auc.integral))
pp3 <- pr.curve(scores.class0 = pb2[chs2], weights.class0 = (1 * (y2[chs2] == 1)), curve = TRUE)
pp4 <- pr.curve(scores.class0 = cpt2[chs2], weights.class0 = (1 * (y2[chs2] == 1)), curve = TRUE)
values_pr <- rbind(values_pr, c(pp3$auc.integral, pp4$auc.integral))
pp5 <- pr.curve(scores.class0 = pb3[chs3], weights.class0 = (1 * (y3[chs3] == 1)), curve = TRUE)
pp6 <- pr.curve(scores.class0 = cpt3[chs3], weights.class0 = (1 * (y3[chs3] == 1)), curve = TRUE)
values_pr <- rbind(values_pr, c(pp5$auc.integral, pp6$auc.integral))
pp7 <- pr.curve(scores.class0 = pb4[chs4], weights.class0 = (1 * (y4[chs4] == 1)), curve = TRUE)
pp8 <- pr.curve(scores.class0 = cpt4[chs4], weights.class0 = (1 * (y4[chs4] == 1)), curve = TRUE)
values_pr <- rbind(values_pr, c(pp7$auc.integral, pp8$auc.integral))
pp9 <- pr.curve(scores.class0 = pb5[chs5], weights.class0 = (1 * (y5[chs5] == 1)), curve = TRUE)
pp10 <- pr.curve(scores.class0 = cpt5[chs5], weights.class0 = (1 * (y5[chs5] == 1)), curve = TRUE)
values_pr <- rbind(values_pr, c(pp9$auc.integral, pp10$auc.integral))

values_pr <- t(values_pr)
values_pr <- as.data.frame(values_pr)
colnames(values_pr) <- c("TS1", "TS2", "TS3", "TS4", "TS5")
rownames(values_pr) <- c("PHACTboost", "CPT-1")


cols <- c("#5B72C7", "#DAA87B")
cols <- c("darkblue", "darkcyan", "chocolate1")
cols <- c("#21457A", "darkcyan")

pdf(file = "EVE_ROC.pdf", width = 9, height = 5)
barplot(as.matrix(values_eve_roc), col = cols, beside = TRUE, ylim = c(0,1.3), yaxt = "n")
legend(12, 1.25, legend = rownames(values_eve_roc), fill = cols, bty = "n", y.intersp = 0.7)
axis(side = 2, at = seq(0,1,0.2), labels = sprintf("%.2f",seq(0,1,0.2)), las = 2)
mtext(side = 2, text = "AUROC", line = 3, cex = 1)
dev.off()

pdf(file = "EVE_PR.pdf", width = 9, height = 5)
barplot(as.matrix(values_eve_pr), col = cols, beside = TRUE, ylim = c(0,1.3), yaxt = "n")
legend(12, 1.25, legend = rownames(values_eve_roc), fill = cols, bty = "n", y.intersp = 0.7)
axis(side = 2, at = seq(0,1,0.2), labels = sprintf("%.2f",seq(0,1,0.2)), las = 2)
mtext(side = 2, text = "AUPR", line = 3, cex = 1)
dev.off()


pdf(file = "CPT1_ROC.pdf", width = 9, height = 5)
barplot(as.matrix(values), col = cols, beside = TRUE, ylim = c(0,1.3), yaxt = "n")
legend(12, 1.25, legend = rownames(values), fill = cols, bty = "n", y.intersp = 0.7)
axis(side = 2, at = seq(0,1,0.2), labels = sprintf("%.2f",seq(0,1,0.2)), las = 2)
mtext(side = 2, text = "AUROC", line = 3, cex = 1)
dev.off()

pdf(file = "CPT1_PR.pdf", width = 9, height = 5)
barplot(as.matrix(values_pr), col = cols, beside = TRUE, ylim = c(0,1.3), yaxt = "n")
legend(12, 1.25, legend = rownames(values_pr), fill = cols, bty = "n", y.intersp = 0.7)
axis(side = 2, at = seq(0,1,0.2), labels = sprintf("%.2f",seq(0,1,0.2)), las = 2)
mtext(side = 2, text = "AUPR", line = 3, cex = 1)
dev.off()
